# name: .NET Core Build

# on:
#   push:
#     branches:
#       - main
#   schedule:
#     - cron: '0 * * * *'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Setup .NET Core
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: '6.0.x'

#     - name: Restore dependencies
#       run: dotnet restore

#     - name: Build
#       run: dotnet build --no-restore

#     - name: Run tests
#       run: dotnet test

name: .NET Core Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: path/to/your/project

    - name: Build
      run: dotnet build --no-restore
      working-directory: path/to/your/project

    - name: Run tests
      run: dotnet test
      working-directory: path/to/your/project
