name: .NET Core Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Updated SDK version to 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: github4women

    - name: Build
      run: dotnet build --no-restore
      working-directory: github4women

    - name: Run tests
      run: dotnet test
      working-directory: github4women